// Generated by CoffeeScript 1.9.1
window.checkCreds = function(form) {
  var nameVar, passwordVar, result;
  nameVar = form.name.value;
  passwordVar = form.password.value;
  result = "";
  if (nameVar === "Taylor" && passwordVar === "iamcool") {
    result = "YOU ARE THE CORRECT PERSON";
  } else {
    result = "INCORRECT CREDENTIALS";
  }
  return document.getElementById("content").innerHTML = result;
};
